### ISSUE TITLE
Bug: choice is not defined

### ISSUE THREAD

**Issue by Thatcooldevguy** [Thatcooldevguy/toolr#1]
Traceback (most recent call last):
  File "main.py", line 39, in <module>
    menu()
  File "main.py", line 13, in menu
    Please enter your choice: """)
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined

**Comment by Thatcooldevguy** [comment]
Possible fix: replace input with raw_input

**Comment by Thatcooldevguy** [comment]
FIXED: useing raw_input works
